apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/rancher/local-path-provisioner/charts
      chart: local-path-provisioner
      targetRevision: 0.0.35
      helm:
        valueFiles:
          - $gitops/apps/csi/local-path-provisioner.values.yaml
    - repoURL: https://github.com/KubeMite/gitops.git
      targetRevision: HEAD
      ref: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true