replicaCount: 3

podSecurityContext:
  runAsNonRoot: true

hostUsers: true

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

helperPod:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Priority class name for the pod
priorityClassName: system-node-critical

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: IfHealthyBudget
