apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: csi
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: seaweedfs_s3_config
      remoteRef:
        key: ef7d92ea-956a-4fcf-a258-b42400997861