apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-ui-credentials
  namespace: csi
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: dfdc39c7-bea5-4a60-b888-b41000f57ff7
    - secretKey: password
      remoteRef:
        key: c89e5733-d091-40b8-9e51-b41000f5a000