# host and port of your SeaweedFs filer
seaweedfsFiler: seaweedfs-filer:8888
storageClassName: seaweedfs
isDefaultStorageClass: true

csiNodeDriverRegistrar:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 150Mi

csiLivenessProbe:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      memory: 150Mi

mountService:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 250Mi

controller:
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      memory: 150Mi
