apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-connector-secret
  namespace: wiki
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: credentials.json
      remoteRef:
        key: bac41f70-c9e2-4bb4-ac03-b42900a3b2cd